[package]
name = "aragog-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["full"]  }
env_logger = "0.9.0"

# ArangoDB
aragog = "0.16.1"
# For missing Grapth type from aragog
arangors_lite = "0.1.0"
serde = "1.0.136"
